### ISSUE TITLE
Security Vulnerability: Sensitive Information Leakage

### ISSUE THREAD

**Issue by bsmedley** [synchronoss/cpo-api#29]
Full stack trace thrown and displayed on screen.
see attached screenshot
Stack trace is printed from cpo-core:
[jar:org.synchronoss.cpo:cpo-core:5.1.1] to [lib/cpo-core-5.1.1.jar]
org.synchronoss.cpo.exporter.XmlExporterServlet
public void doPost...
} catch (Exception e)
{ response.setContentType(HTML_CONTENT_TYPE); pw.println("<html><head><title>ERROR</title></head><p>Error generating xml: <pre>"); e.printStackTrace(pw); pw.println("</pre></p></html>"); }
![screen shot 2016-04-22 at 15 06 13](https://cloud.githubusercontent.com/assets/12415625/16117355/b19a8db6-339f-11e6-9418-cbe4834509e5.png)

**Comment by berryware** [comment]
Do you just want the stack trace removed? Are you good with it saying that no meta descriptor is defined?

**Comment by bsmedley** [comment]
Yeah that’s what we did for other internal errors. This came out of a pen test GIS had done.

**Comment by berryware** [comment]
Fixed and merged
